### ISSUE TITLE
Port to Web

### ISSUE THREAD

**Issue by Mar0xy** [vtheskeleton/statuslog-mobile#1]
Considering this is written in React and uses Expo it should be easy for this to also be turned into a Webapp by swapping out react native for normal react and I think this should be considered. If you don't plan on doing I wouldn't mind porting it.

**Comment by vtheskeleton** [comment]
I'm not quite sure why you would want to port it to Web, Adam already provides quite good tools (statuslog section on home.omg.lol and the bookmarklet) for statusloggery.

There are a couple things you would need to consider if porting to the web however:

- The app utilizes secure store, which does not exist on web
- The app utilizes MaskedView, which does not exist on web
- Probably something else too but i have forgotten
- The UI is designed to make sense for mobile devices, not web apps

I believe it would be far more efficient to just write something new for a web app

**Comment by vtheskeleton** [comment]
I just dont see the point in taking the mobile app to the web when there are official web things that dont require you to hand over full control of your omgalol to a random blob on the internet, go for it if you want but I suggest taking time to think about if it makes any sense to do so.
